load("@bazel_skylib//rules:build_test.bzl", "build_test")
load("@rules_go//go:def.bzl", "go_binary", "go_library", "go_test")

go_library(
    name = "registry_lib",
    srcs = [
        "flagtypes.go",
        "registry.go",
    ],
    importpath = "github.com/bazel-contrib/rules_img/img_tool/cmd/registry",
    visibility = ["//visibility:private"],
    deps = [
        "//pkg/auth/credential",
        "//pkg/auth/protohelper",
        "//pkg/proto/blobcache",
        "//pkg/registry",
        "//pkg/registry/s3store",
        "//pkg/serve/blobcache",
        "//pkg/serve/registry",
        "//pkg/serve/registry/reapi",
        "//pkg/serve/registry/s3",
        "//pkg/serve/registry/upstream",
        "@com_github_aws_aws_sdk_go_v2_config//:config",
        "@com_github_aws_aws_sdk_go_v2_service_s3//:s3",
        "@com_github_google_go_containerregistry//pkg/v1:pkg",
        "@org_golang_google_grpc//:grpc",
    ],
)

version_x_defs = {
    "github.com/bazel-contrib/rules_img/img_tool/pkg/version.Version": module_version() or "dev",
}

go_binary(
    name = "registry",
    embed = [":registry_lib"],
    pure = "on",
    visibility = ["//visibility:public"],
    x_defs = version_x_defs,
)

go_test(
    name = "registry_test",
    srcs = ["flagtypes_test.go"],
    embed = [":registry_lib"],
)

build_test(
    name = "test",
    targets = [":registry"],
)
